-- ===========================================================================
-- Demo schema of a "financial transaction orchestrator" for local runs.
-- Also shows the recommended permission model for the console:
--   user console: SELECT on the schema, INSERT only on the tables that need it,
--   its own schema admin_console for the audit log.
-- ===========================================================================

create schema orch;

create type orch.payment_status as enum ('CREATED', 'VALIDATED', 'SENT_TO_CORE', 'COMPLETED', 'FAILED', 'CANCELLED');
create type orch.step_status as enum ('PENDING', 'RUNNING', 'DONE', 'ERROR', 'SKIPPED');

create table orch.payment (
    id              bigint generated by default as identity primary key,
    payment_uid     uuid           not null default gen_random_uuid() unique,
    external_id     varchar(64)    not null,
    status          orch.payment_status not null default 'CREATED',
    amount          numeric(19, 2) not null check (amount > 0),
    currency        char(3)        not null default 'RUB',
    payer_account   varchar(20)    not null,
    payee_account   varchar(20)    not null,
    payee_bic       varchar(9)     not null,
    purpose         text,
    attributes      jsonb          not null default '{}'::jsonb,
    created_at      timestamptz    not null default now(),
    updated_at      timestamptz    not null default now()
);
comment on table orch.payment is 'Платёж — корневая сущность процесса';
comment on column orch.payment.external_id is 'Идентификатор во внешней системе (ДБО)';
create index payment_status_idx on orch.payment (status, created_at desc);
create index payment_external_idx on orch.payment (external_id);

create table orch.payment_step (
    id           bigint generated always as identity primary key,
    payment_id   bigint      not null references orch.payment (id),
    step_no      int         not null,
    step_name    varchar(64) not null,
    status       orch.step_status not null default 'PENDING',
    attempts     int         not null default 0,
    last_error   text,
    started_at   timestamptz,
    finished_at  timestamptz,
    duration_ms  bigint generated always as ((extract(epoch from (finished_at - started_at)) * 1000)::bigint) stored,
    unique (payment_id, step_no)
);
comment on table orch.payment_step is 'Шаги оркестрации платежа';

create table orch.outbox (
    id           bigserial primary key,
    aggregate_id varchar(64) not null,
    topic        varchar(128) not null,
    msg_key      varchar(128),
    payload      jsonb       not null,
    headers      jsonb,
    created_at   timestamptz not null default now(),
    sent_at      timestamptz
);
comment on table orch.outbox is 'Transactional outbox → Kafka';

create table orch.retry_task (
    id           bigserial primary key,
    payment_id   bigint      not null references orch.payment (id),
    step_name    varchar(64) not null,
    run_at       timestamptz not null default now(),
    reason       text,
    created_by   varchar(64) not null default current_user
);
comment on table orch.retry_task is 'Задания на повтор шага — сюда сопровождение вставляет строки вручную';

create table orch.dictionary_currency (
    code   char(3) primary key,
    name   text not null,
    active boolean not null default true
);

-- partitioned event log table
create table orch.event_log (
    id          bigserial,
    payment_id  bigint,
    event_type  varchar(64) not null,
    payload     jsonb,
    created_at  timestamptz not null default now(),
    primary key (id, created_at)
) partition by range (created_at);
create table orch.event_log_2026 partition of orch.event_log
    for values from ('2026-01-01') to ('2027-01-01');
create table orch.event_log_default partition of orch.event_log default;

create view orch.v_failed_payments as
select p.id, p.external_id, p.amount, p.currency, p.created_at, s.step_name, s.last_error
from orch.payment p
join orch.payment_step s on s.payment_id = p.id and s.status = 'ERROR'
where p.status = 'FAILED';

-- ------------------------------------------------------------------ data
insert into orch.dictionary_currency (code, name) values
    ('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('CNY', 'Китайский юань');

insert into orch.payment (external_id, status, amount, currency, payer_account, payee_account, payee_bic,
                          purpose, attributes, created_at)
select 'DBO-' || lpad(g::text, 8, '0'),
       (array['CREATED','VALIDATED','SENT_TO_CORE','COMPLETED','COMPLETED','COMPLETED','FAILED'])[1 + g % 7]::orch.payment_status,
       round((random() * 1000000 + 1)::numeric, 2),
       (array['RUB','RUB','RUB','USD','CNY'])[1 + g % 5],
       '40702810' || lpad((g * 13)::text, 12, '0'),
       '40817810' || lpad((g * 17)::text, 12, '0'),
       (array['044525225','044525974','044525593'])[1 + g % 3],
       'Оплата по договору №' || g,
       jsonb_build_object('channel', (array['WEB','MOBILE','API'])[1 + g % 3], 'priority', g % 3, 'trace', md5(g::text)),
       now() - (g || ' minutes')::interval
from generate_series(1, 5000) g;

insert into orch.payment_step (payment_id, step_no, step_name, status, attempts, last_error, started_at, finished_at)
select p.id, s.no, s.name,
       case when p.status = 'FAILED' and s.no = 3 then 'ERROR'::orch.step_status
            when p.status = 'COMPLETED' then 'DONE'::orch.step_status
            when s.no = 1 then 'DONE'::orch.step_status
            else 'PENDING'::orch.step_status end,
       case when p.status = 'FAILED' and s.no = 3 then 3 else 1 end,
       case when p.status = 'FAILED' and s.no = 3 then 'CORE_TIMEOUT: no response from ABS in 30s' end,
       p.created_at + (s.no || ' seconds')::interval,
       p.created_at + (s.no || ' seconds')::interval + ((random() * 900)::int || ' milliseconds')::interval
from orch.payment p
cross join (values (1, 'VALIDATE'), (2, 'AML_CHECK'), (3, 'SEND_TO_CORE'), (4, 'NOTIFY')) as s(no, name);

insert into orch.outbox (aggregate_id, topic, msg_key, payload, created_at, sent_at)
select p.external_id, 'payments.events', p.external_id,
       jsonb_build_object('paymentId', p.external_id, 'status', p.status, 'amount', p.amount),
       p.created_at, case when p.id % 10 = 0 then null else p.created_at + interval '1 second' end
from orch.payment p where p.id <= 1000;

insert into orch.event_log (payment_id, event_type, payload, created_at)
select p.id, 'STATUS_CHANGED', jsonb_build_object('to', p.status), p.created_at
from orch.payment p where p.id <= 2000;

analyze;

-- ------------------------------------------------------- console user
create role console login password 'console';
grant usage on schema orch to console;
grant select on all tables in schema orch to console;
grant insert on orch.retry_task, orch.outbox, orch.payment, orch.dictionary_currency to console;
grant usage on all sequences in schema orch to console;
-- UPDATE — only on the individual columns support really needs to change
grant update (run_at, reason) on orch.retry_task to console;
grant update (status, attributes) on orch.payment to console;
grant update (sent_at) on orch.outbox to console;

create schema admin_console authorization console;
